# Generated by Django 2.1.7 on 2019-03-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='name',
            field=models.CharField(default='set_name', max_length=50),
        ),
    ]
